######################################################################
# Automatically generated by qmake (2.01a) Wed May 6 15:04:54 2015
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
